-- this should possibly be applied after migration
-- as of this writing we are not doing it
-- lets stash this in the repo just in case
--
-- people keep saying (incorrectly)
--   "there is no other way to add IDs"
-- but these sequences are clearly being called by the cscl
--    maintenance system software. This software will not exist.
--    so there HAS to be some other way
--
GRANT SELECT ON CSCL.SEQ_ADDRESSPOINT_ID TO BASIC;
GRANT SELECT ON CSCL.SEGMENTID TO BASIC;
GRANT SELECT ON CSCL.SEQ_ACCESSPOINT_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_ADDRESSPOINT_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_COMMONPLACE_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_COMPACCESSPOINT_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_COMPLEX_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_ENTRANCEPOINT_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_FEATURENAMEID TO BASIC;
GRANT SELECT ON CSCL.SEQ_GENERIC_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_LDF_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_LDF_NUM TO BASIC;
GRANT SELECT ON CSCL.SEQ_LINK_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_NODE_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_NYPD_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_PHYSICAL_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_RAIL_SUBWAY TO BASIC;
GRANT SELECT ON CSCL.SEQ_RAILSTATION_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_SEGMENT_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_STREETNAMEID TO BASIC;
GRANT SELECT ON CSCL.SEQ_SUBWAYSTATION_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_TRANSITBOOTH_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_TRANSITEMERGENCY_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_TRANSITENTRANCE_ID TO BASIC;
GRANT SELECT ON CSCL.SEQ_TURNID TO BASIC;